---

- name: Enable CRB (RHEL)
  community.general.rhsm_repository:
    name: "codeready-builder-for-rhel-{{ ansible_facts.distribution_major_version }}-{{ ansible_facts.architecture }}-rpms"

- name: Install EPEL (RHEL)
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm"
    state: present
